# Generated by Django 4.0.2 on 2022-02-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bid_document_job_category_profile_project_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_define',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.job_category'),
        ),
    ]
