# Generated by Django 4.0.2 on 2022-02-11 16:33

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bid_document_job_category_profile_project_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_document',
            name='document',
            field=models.FileField(null=True, upload_to=pathlib.PureWindowsPath('C:/Users/pc/Desktop/6th Sem/minor/Project/minor_project/static/assets/bid_documents')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/pc/Desktop/6th Sem/minor/Project/minor_project/static/assets/profile_images')),
        ),
        migrations.AlterField(
            model_name='project_document',
            name='document',
            field=models.FileField(null=True, upload_to=pathlib.PureWindowsPath('C:/Users/pc/Desktop/6th Sem/minor/Project/minor_project/static/assets/project_documents')),
        ),
    ]
