# Generated by Django 4.0.2 on 2022-02-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bid_document_document_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='users',
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ManyToManyField(to='api.Profile'),
        ),
    ]
