# Generated by Django 3.2.5 on 2022-02-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
