# Generated by Django 4.0.2 on 2022-02-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid_document',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='project_bid',
            name='max_offer',
        ),
        migrations.RemoveField(
            model_name='project_bid',
            name='min_offer',
        ),
        migrations.RemoveField(
            model_name='project_document',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='users',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AddField(
            model_name='project_bid',
            name='offered_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='project_define',
            name='projectFile',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hours_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='project_bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='project_define',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='critic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_given', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_received', to='api.profile'),
        ),
    ]
