# Generated by Django 4.0.2 on 2022-02-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_skill_profile_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ManyToManyField(to='api.Profile'),
        ),
    ]
