# Generated by Django 4.0.2 on 2022-02-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_profile_skills_skill_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.project_bid'),
        ),
    ]
