# Generated by Django 4.0.2 on 2022-02-08 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jobcategory_field1_jobcategory_field2_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participant',
        ),
        migrations.AddField(
            model_name='room',
            name='freelancerUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancerUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
