# Generated by Django 4.0.2 on 2022-02-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_groups_user_user_permissions'),
        ('api', '0008_alter_project_freelancer'),
    ]

    operations = [
    ]
