# Generated by Django 4.0.2 on 2022-02-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bid_document_job_category_project_bid_project_define_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_document',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project_document',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
