# Generated by Django 4.0.2 on 2022-03-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_project_define_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_images/'),
        ),
    ]
