# Generated by Django 4.0.2 on 2022-02-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
