# Generated by Django 4.0.2 on 2022-02-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
