# Generated by Django 4.0.2 on 2022-02-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dummyuser_alter_user_username_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyuser',
            name='username',
        ),
    ]
