# Generated by Django 4.0.2 on 2022-03-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_project_define_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder_bids', to='api.profile'),
        ),
    ]
