# Generated by Django 4.0.2 on 2022-03-03 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_message_options_message_created_message_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
